Embed Video Project
nriqu322/Youtube-videoplayer pull request #4
Opened 2020-01-15 16:03 UTC by Salvador-ON

First Pull Request

2020-01-15 17:49 UTC, pelzolga123 commented on index.html
> +                    <img src="media/yt-ico.png" alt="youtube-ico" id="youtube-ico">
Id should be unique, use class instead.

2020-01-15 17:50 UTC, pelzolga123 commented on index.html
> +                <img src="media/yt-ico.png" alt="youtube-ico" id="youtube-ico">
Id should be unique, use class instead.

2020-01-15 17:50 UTC, pelzolga123 commented on index.html
> +                    <li id="first-line">About</li>
Id should be unique, use class instead.

2020-01-15 17:50 UTC, pelzolga123 commented on index.html
> +                    <li id="first-line">Terms</li>
Id should be unique, use class instead.

2020-01-15 17:51 UTC, pelzolga123 requested changes
Project requires changes.

2020-01-15 17:51 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
Here are the changes, you need to do before this project can be approved:
* [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
* [ ] Navbar should have a `<button>` tag that represents the search button, right now you have `<input>` tag there ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/search_button_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ] Subscribe should be a button, right now it is just an image ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

* [ ] Pull Request should have a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] No ID selectors for multiple elements. Id should always be unique, use class instead.

[OPTIONAL]
* `info-section` will look better if you add a little padding to it.
*  It's a good practice to use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-01-15 20:47 UTC, nriqu322 commented
We solve every checkbox indicated above.

-use buttons instead of images.
-correct use of ID and classes
-no errors in validator

2020-01-16 00:25 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team, You have done a great job with this project. :clap:

2020-01-16 14:37 UTC, merged